### ISSUE TITLE
Need to DCO sign-off all previous commits

### ISSUE THREAD

**Issue by TimoGlastra** [auer-martin/dcql#25]
I think the github bot should be signed of with the github bot email (like we do in credo)

**Comment by auer-martin** [comment]
done

**Comment by TimoGlastra** [comment]
I seems the github actions commits are not signed off yet (which will cause issues with the DCO bot i think).

The credo repository already has this correctly setup i think. it's a bit annoying to setup but a requirement for Linux Foundation
